// Generated by CoffeeScript 2.3.1
(function() {
  var BindingsClass, BindingsInstance, ValueSetter;

  BindingsClass = {
    model: 'model',
    bindings: {}
  };

  ValueSetter = class ValueSetter {
    constructor(context) {
      this.context = context;
    }

    setValue(element, value, setter) {
      if (typeof setter === 'string') {
        setter = this.context.proxy(this.context[setter]);
      }
      setter = setter || (e, v) => {
        return this._standardSetter(e, v);
      };
      return setter(element, value);
    }

    getValue(element, getter) {
      if (typeof getter === 'string') {
        getter = this.context.proxy(this.context[getter]);
      }
      getter = getter || (e, v) => {
        return this._standardGetter(e, v);
      };
      return getter(element);
    }

    _standardGetter(element) {
      var name, self;
      self = this;
      return (typeof self[name = `_${element.attr('type')}Get`] === "function" ? self[name](element) : void 0) || element.val();
    }

    _standardSetter(element, value) {
      var self;
      self = this;
      return element.each(function() {
        var el, name;
        el = $(this);
        return (typeof self[name = `_${el.attr('type')}Set`] === "function" ? self[name](el, value) : void 0) || el.val(value);
      });
    }

    _checkboxSet(element, value) {
      if (value) {
        return element.prop('checked', 'checked');
      } else {
        return element.prop('checked', '');
      }
    }

    _checkboxGet(element) {
      return element.is(':checked');
    }

  };

  BindingsInstance = {
    getModel: function() {
      return this[this.modelVar];
    },
    setModel: function(model) {
      return this[this.modelVar] = model;
    },
    walkBindings: function(fn) {
      var field, ref, results, selector;
      ref = this.bindings;
      results = [];
      for (selector in ref) {
        field = ref[selector];
        results.push(fn(selector, field));
      }
      return results;
    },
    applyBindings: function() {
      this.valueSetter = new ValueSetter(this);
      return this.walkBindings((selector, field) => {
        if (!field.direction || field.direction === 'model') {
          this._bindModelToEl(this.getModel(), field, selector);
        }
        if (!field.direction || field.direction === 'element') {
          return this._bindElToModel(this.getModel(), field, selector);
        }
      });
    },
    _getField: function(value) {
      if (typeof value === 'string') {
        return value;
      } else {
        return value.field;
      }
    },
    _forceModelBindings: function(model) {
      return this.walkBindings((selector, field) => {
        return this.valueSetter.setValue(this.$(selector), model[this._getField(field)], field.setter);
      });
    },
    changeBindingSource: function(model) {
      this.getModel().unbind('change');
      this.walkBindings((selector) => {
        if (selector === 'self') {
          selector = false;
        }
        return this.el.off('change', selector);
      });
      this.setModel(model);
      this._forceModelBindings(model);
      return this.applyBindings();
    },
    _bindModelToEl: function(model, field, selector) {
      var self;
      self = this;
      if (selector === 'self') {
        selector = false;
      }
      return this.el.on('change', selector, function() {
        return model[self._getField(field)] = self.valueSetter.getValue($(this), field.getter);
      });
    },
    _bindElToModel: function(model, field, selector) {
      return model.bind('change', () => {
        return this.valueSetter.setValue(this.$(selector), model[this._getField(field)], field.setter);
      });
    }
  };

  Spine.Bindings = {
    extended: function() {
      this.extend(BindingsClass);
      return this.include(BindingsInstance);
    }
  };

}).call(this);

//# sourceMappingURL=bindings.js.map
